default_stages: [pre-commit,pre-push]

repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.8
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        types: [go]
        pass_filenames: false
        args: ["--timeout=1m"]
