version: 0.0.2
config:
  project:
    name: "my-avs"
    version: "0.1.0"
    context: "devnet"
    project_uuid: ""
    telemetry_enabled: false
    templateBaseUrl: "https://github.com/Layr-Labs/hourglass-avs-template"
    templateVersion: "v0.0.10"
