architectures:
  task:
    languages:
      go:
        baseUrl: "https://github.com/Layr-Labs/hourglass-avs-template"
        version: "95f9067bd35b770e989d7d6442003e405d7639ae"
      ts:
        baseUrl: ""
        version: ""
      rust:
        baseUrl: ""
        version: ""
