name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

jobs:
  Test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devkit-cli
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        run: |
          go mod tidy
          make build
